"""initial migration

Revision ID: 2217af24be5b
Revises: 
Create Date: 2025-07-31 15:42:51.245996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2217af24be5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('production_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('user', 'designer', 'admin', name='user_roles'), nullable=False),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.Column('enhanced_prompt', sa.String(length=2000), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('result_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('item_type', sa.Enum('BANNER', 'STANDEE', 'BILLBOARD', 'DIGITAL', name='producttype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('preview_url', sa.String(length=500), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('designer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'premium', name='subscription_plans'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('remaining_generations', sa.Integer(), nullable=False),
    sa.CheckConstraint("NOT (plan = 'free' AND remaining_generations > 5)", name='check_free_plan_limits'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('created', 'paid', 'production', 'shipped', 'completed', name='order_status'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('design_specs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('production_deadline', sa.DateTime(), nullable=True),
    sa.Column('production_errors', sa.JSON(), nullable=True),
    sa.Column('factory_id', sa.Uuid(), nullable=True),
    sa.Column('market_item_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['market_item_id'], ['market_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('subscriptions')
    op.drop_table('market_items')
    op.drop_table('generations')
    op.drop_table('users')
    op.drop_table('factories')
    # ### end Alembic commands ###
