"""add_auth_fields

Revision ID: 24_08_2025_add_auth_fields
Revises: 12e666579334
Create Date: 2025-08-24 18:48:37.470499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24_08_2025_add_auth_fields'
down_revision: Union[str, Sequence[str], None] = '12e666579334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'device_id')
    op.drop_column('users', 'is_guest')
    # ### end Alembic commands ###