"""initial migration

Revision ID: 466b80ceb431
Revises: 
Create Date: 2025-08-08 14:54:50.938607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466b80ceb431'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('production_capacity', sa.Integer(), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint("role IN ('user', 'designer', 'admin')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.Column('enhanced_prompt', sa.String(length=2000), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('result_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('external_task_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='check_generation_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('preview_url', sa.String(length=500), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('designer_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("item_type IN ('BANNER', 'STANDEE', 'BILLBOARD', 'DIGITAL')", name='check_product_type'),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('unread', 'read', 'archived')", name='check_notification_status'),
    sa.CheckConstraint("type IN ('system', 'order', 'payment', 'support')", name='check_notification_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('remaining_generations', sa.Integer(), nullable=False),
    sa.CheckConstraint("NOT (plan = 'free' AND remaining_generations > 5)", name='check_free_plan_limits'),
    sa.CheckConstraint("plan IN ('free', 'pro', 'premium')", name='check_subscription_plan'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('production_deadline', sa.DateTime(), nullable=True),
    sa.Column('factory_id', sa.Uuid(), nullable=True),
    sa.Column('market_item_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('created', 'paid', 'production', 'shipped', 'completed', 'cancelled')", name='check_valid_order_status'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['market_item_id'], ['market_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Уникальный идентификатор сообщения'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='ID связанного заказа'),
    sa.Column('sender_id', sa.UUID(), nullable=False, comment='ID отправителя сообщения'),
    sa.Column('message', sa.Text(), nullable=False, comment='Текст сообщения'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='Список URL вложений (опционально)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время создания сообщения'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Флаг прочтения сообщения'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'canceled')", name='check_payment_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('chat_messages')
    op.drop_table('orders')
    op.drop_table('subscriptions')
    op.drop_table('notifications')
    op.drop_table('market_items')
    op.drop_table('generations')
    op.drop_table('users')
    op.drop_table('factories')
    # ### end Alembic commands ###
